# Setup
title:        xmake
tagline:      A make-like build utility based on Lua
tagline_cn:   一个基于Lua的轻量级自动构建工具
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       waruqi
  url:        http://tboox.org 

#Others
markdown: kramdown

# multiple-languages
gems:               ['jekyll-paginate', 'jekyll-multiple-languages']
languages:          ['en', 'cn']
language_default:   'en'
