name: Cosmocc (macOS)

on:
  pull_request:
  push:
  release:
    types: [published]
jobs:
  build:
    strategy:
      matrix:
        os: [macos-13]
        arch: [x86_64]

    runs-on: ${{ matrix.os }}

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Cosmocc-macOS-${{ matrix.arch }}
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Prepare local xmake
        run: cp -rf . ../xmake-source
        
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: local#../xmake-source

      - uses: bjia56/setup-cosmocc@main
        with:
          version: "4.0.2"

      - name: Installation
        run: |
          brew install dmd
          brew install dub

      - name: Build
        run: |
          cd core
          xmake f -p linux --cosmocc=y --embed=y -y -cvD
          xmake -v
          cd ..

      # In the tests, cmake tries to use make from the cosmopolitan toolchain and fails, so uninstall it
      - name: Remove cosmocc
        run: |
          INSTALL_DIR="${{runner.temp}}/cosmocc-4.0.2"
          echo "Removing cosmocc from PATH"
          echo "::remove-path::${INSTALL_DIR}/bin"
          rm -r "${INSTALL_DIR}"

      - name: Tests
        run: |
          ls -l core/build/
          core/build/xmake --version
          core/build/xmake lua -v -D tests/run.lua

      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: xmake-cosmocc
          path: core/build/xmake
