name: Linux (Luajit)

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Linux-Luajit
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest
      - uses: little-core-labs/get-git-tag@v3.0.2
        id: tagName

      - name: Installation
        run: |
          make RUNTIME=luajit
          ./scripts/get.sh __local__ __install_only__
          source ~/.xmake/profile
          xmake --version

      - name: Prepare
        run: |
          sudo apt install -y build-essential llvm

      - name: Tests
        run: |
          xmake lua -v -D tests/run.lua
          xrepo --version

