name: Ubuntu (Arm)

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-UbuntuArm
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset

      - uses: docker://multiarch/ubuntu-core:armhf-bionic
        with:
          args: >
            bash -c
            "uname -a &&
            apt update && apt install -y unzip &&
            cd /github/workspace &&
            ./scripts/get.sh __local__ &&
            source ~/.xmake/profile &&
            export XMAKE_ROOT=y &&
            export XMAKE_TMPDIR=/tmp &&
            xmake lua -v -D tests/run.lua && xrepo --version"

